/* Copyright (c) 2013-2020, MUSEN Development Team. All rights reserved.
   This file is part of MUSEN framework http://msolids.net/musen.
   See LICENSE file for license and warranty information. */

#pragma once

#define MACRO_CONCAT(X,Y) MACRO_CONCAT_L2(X,Y)
#define MACRO_CONCAT_L2(X,Y) X ## Y
#define MACRO_TOSTRING(X) MACRO_TOSTRING_L2(X)
#define MACRO_TOSTRING_L2(X) #X

////////////////////////////////////////////////////////////////////////////////////////////////////
/// Set of helper macros to iterate over arguments passed to a variadic macro.

#define EXPAND(x) x
#define FOR_EACH_VA_SELECT(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,NAME,...) NAME

////////////////////////////////////////////////////////////////////////////////////////////////////
// Use arguments directly as values: a call
// FOR_EACH_VA_VAL(vector.push_back, val1, val2, val3)
// will be evaluated as
// vector.push_back(val1); vector.push_back(val2); vector.push_back(val3);

#define FE_VA_VAL_00(OPERATION, ARGUMENT) OPERATION(ARGUMENT);
#define FE_VA_VAL_01(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_00(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_02(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_01(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_03(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_02(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_04(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_03(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_05(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_04(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_06(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_05(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_07(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_06(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_08(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_07(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_09(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_08(OPERATION,__VA_ARGS__))
#define FE_VA_VAL_10(OPERATION, ARGUMENT, ...) OPERATION(ARGUMENT); EXPAND(FE_VA_VAL_09(OPERATION,__VA_ARGS__))
#define FOR_EACH_VA_VAL(OPERATION,...) EXPAND(FOR_EACH_VA_SELECT(__VA_ARGS__,FE_VA_VAL_10,FE_VA_VAL_09,FE_VA_VAL_08,FE_VA_VAL_07,FE_VA_VAL_06,FE_VA_VAL_05,FE_VA_VAL_04,FE_VA_VAL_03,FE_VA_VAL_02,FE_VA_VAL_01,FE_VA_VAL_00,)(OPERATION,__VA_ARGS__))

////////////////////////////////////////////////////////////////////////////////////////////////////
// Use arguments as references: a call
// FOR_EACH_VA_REF(vector.push_back, val1, val2, val3)
// will be evaluated as
// vector.push_back(&val1); vector.push_back(&val2); vector.push_back(&val3);

#define FE_VA_REF_00(OPERATION, ARGUMENT) OPERATION(&ARGUMENT);
#define FE_VA_REF_01(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_00(OPERATION,__VA_ARGS__))
#define FE_VA_REF_02(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_01(OPERATION,__VA_ARGS__))
#define FE_VA_REF_03(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_02(OPERATION,__VA_ARGS__))
#define FE_VA_REF_04(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_03(OPERATION,__VA_ARGS__))
#define FE_VA_REF_05(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_04(OPERATION,__VA_ARGS__))
#define FE_VA_REF_06(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_05(OPERATION,__VA_ARGS__))
#define FE_VA_REF_07(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_06(OPERATION,__VA_ARGS__))
#define FE_VA_REF_08(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_07(OPERATION,__VA_ARGS__))
#define FE_VA_REF_09(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_08(OPERATION,__VA_ARGS__))
#define FE_VA_REF_10(OPERATION, ARGUMENT, ...) OPERATION(&ARGUMENT); EXPAND(FE_VA_REF_09(OPERATION,__VA_ARGS__))
#define FOR_EACH_VA_REF(OPERATION,...) EXPAND(FOR_EACH_VA_SELECT(__VA_ARGS__,FE_VA_REF_10,FE_VA_REF_09,FE_VA_REF_08,FE_VA_REF_07,FE_VA_REF_06,FE_VA_REF_05,FE_VA_REF_04,FE_VA_REF_03,FE_VA_REF_02,FE_VA_REF_01,FE_VA_REF_00,)(OPERATION,__VA_ARGS__))

////////////////////////////////////////////////////////////////////////////////////////////////////
// Use arguments as references: a call
// FOR_EACH_VA_PTR(vector.push_back, val1, val2, val3)
// will be evaluated as
// vector.push_back(*val1); vector.push_back(*val2); vector.push_back(*val3);

#define FE_VA_PTR_00(OPERATION, ARGUMENT) OPERATION(*ARGUMENT);
#define FE_VA_PTR_01(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_00(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_02(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_01(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_03(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_02(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_04(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_03(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_05(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_04(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_06(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_05(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_07(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_06(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_08(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_07(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_09(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_08(OPERATION,__VA_ARGS__))
#define FE_VA_PTR_10(OPERATION, ARGUMENT, ...) OPERATION(*ARGUMENT); EXPAND(FE_VA_PTR_09(OPERATION,__VA_ARGS__))
#define FOR_EACH_VA_PTR(OPERATION,...) EXPAND(FOR_EACH_VA_SELECT(__VA_ARGS__,FE_VA_PTR_10,FE_VA_PTR_09,FE_VA_PTR_08,FE_VA_PTR_07,FE_VA_PTR_06,FE_VA_PTR_05,FE_VA_PTR_04,FE_VA_PTR_03,FE_VA_PTR_02,FE_VA_PTR_01,FE_VA_PTR_00,)(OPERATION,__VA_ARGS__))

////////////////////////////////////////////////////////////////////////////////////////////////////
// Use arguments to create definitions: a call
// FOR_EACH_VA_DEF(int, 0, val1, val2, val3)
// will be evaluated as
// int val1{0}; int val2{0}; int val3{0};

#define FE_VA_DEF_00(TYPE, INIT_VALUE, ARGUMENT) TYPE ARGUMENT{INIT_VALUE};
#define FE_VA_DEF_01(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_00(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_02(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_01(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_03(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_02(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_04(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_03(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_05(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_04(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_06(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_05(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_07(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_06(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_08(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_07(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_09(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_08(TYPE, INIT_VALUE,__VA_ARGS__))
#define FE_VA_DEF_10(TYPE, INIT_VALUE, ARGUMENT, ...) TYPE ARGUMENT {INIT_VALUE}; EXPAND(FE_VA_DEF_09(TYPE, INIT_VALUE,__VA_ARGS__))
#define FOR_EACH_VA_DEF(TYPE,INIT_VALUE,...) EXPAND(FOR_EACH_VA_SELECT(__VA_ARGS__,FE_VA_DEF_10,FE_VA_DEF_09,FE_VA_DEF_08,FE_VA_DEF_07,FE_VA_DEF_06,FE_VA_DEF_05,FE_VA_DEF_04,FE_VA_DEF_03,FE_VA_DEF_02,FE_VA_DEF_01,FE_VA_DEF_00,)(TYPE, INIT_VALUE,__VA_ARGS__))
